import streamlit as st
st.write("hello World")
st.title("My First Streamlit App")
st.write("Welcome")
st.write("Hello Vineela")
st.write("Hello dev branch first commit")
st.write("Hello, first merge")
st.write("First pull and push")
st.write("Verifying push and Pull")
st.write("Verifying merge")